version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - magento

  php:
    image: php:7.4-fpm
    build :
      context : ./docker/php
      dockerfile : Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - elasticsearch
    networks:
      - magento

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    networks:
      - magento

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks :
      - magento

volumes:
  db_data:
  es_data:

networks:
  magento: